package eu.pb4.rayon.api.event.collision;

import eu.pb4.rayon.api.PhysicsElement;
import eu.pb4.rayon.impl.bullet.collision.body.ElementRigidBody;
import eu.pb4.rayon.impl.bullet.collision.body.TerrainRigidBody;
import net.fabricmc.fabric.api.event.Event;
import net.fabricmc.fabric.api.event.EventFactory;

/**
 * @since 1.0.0
 */
public class ElementCollisionEvents {
    public static final Event<BlockCollision> BLOCK_COLLISION = EventFactory.createArrayBacked(BlockCollision.class, (events) -> (element, terrainRigidBody, impulse) -> {
        for (var e : events) {
            e.onCollide(element, terrainRigidBody, impulse);
        }
    });
    public static final Event<BlockCollision> FLUID_COLLISION = EventFactory.createArrayBacked(BlockCollision.class, (events) -> (element, terrainRigidBody, impulse) -> {
        for (var e : events) {
            e.onCollide(element, terrainRigidBody, impulse);
        }
    });
    public static final Event<ElementCollision> ELEMENT_COLLISION = EventFactory.createArrayBacked(ElementCollision.class, (events) -> (element, terrainRigidBody, impulse) -> {
        for (var e : events) {
            e.onCollide(element, terrainRigidBody, impulse);
        }
    });;

    private ElementCollisionEvents() { }

    @FunctionalInterface
    public interface BlockCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link }.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface FluidCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link TerrainRigidBody}.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface ElementCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with another {@link ElementRigidBody}.
         * @param element1 the first element
         * @param element2 the second element
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element1, PhysicsElement element2, float impulse);
    }
}
